version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    # environment:
      # - FLASK_ENV=production
      # - FLASK_APP=app.py
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/data:/app/data
    networks:
      - app-network
    restart: unless-stopped

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000  
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  uploads:
  data:
